### ISSUE TITLE
Add Content for Call for Speakers

### ISSUE THREAD

**Issue by Kriesse** [jsconf/2018.jsconf.eu#12]
Needs proofreading, links, final polish.

**Comment by Kriesse** [comment]
@janl I added the preliminary content for your CfS, it's ready for editing here in branch `master`:
https://github.com/jsconf/2018.jsconf.eu/tree/master/contents/copy/cfs

FYI:
- Each chapter has its own .md file due to layout reasons, they are plugged together in `templates/pages/call-for-speakers.html.njk`
- I did a first proofread and replaced instances of `CSS` with `JS`, and `2017` with `2018`
- Some links are not links yet, I marked those with `[link]`

**Comment by janl** [comment]
https://github.com/jsconf/2018.jsconf.eu/pull/23
