### ISSUE TITLE
Add Content for Code of Conduct

### ISSUE THREAD

**Issue by Kriesse** [jsconf/2018.jsconf.eu#13]
Ready for content editing:
https://github.com/jsconf/2018.jsconf.eu/tree/master/contents/copy/coc

**Comment by Kriesse** [comment]
@fox suggested to switch to this CoC template: http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy
I agree that it's more actionable and more informative when shared with volunteers and staff.

**Comment by janl** [comment]
https://github.com/jsconf/2018.jsconf.eu/pull/24
