### ISSUE TITLE
Add Content for Scholarships

### ISSUE THREAD

**Issue by Kriesse** [jsconf/2018.jsconf.eu#14]
Ready for content editing:
https://github.com/jsconf/2018.jsconf.eu/tree/master/contents/copy/scholarships

**Comment by Kriesse** [comment]
@janl Can you add Simone to this repo so she can help?

**Comment by Kriesse** [comment]
@simonehaas I added the preliminary content. It needs proofreading and some links are missing or only make sense for cssconf.
https://github.com/jsconf/2018.jsconf.eu/blob/master/contents/copy/scholarships/scholarships.md

**Comment by cramforce** [comment]
Simone: You now have write access.

**Comment by janl** [comment]
closing in favour of https://github.com/jsconf/2018.jsconf.eu/pull/21
