### ISSUE TITLE
Add Content for Sponsors

### ISSUE THREAD

**Issue by Kriesse** [jsconf/2018.jsconf.eu#15]
Ready for content editing:
https://github.com/jsconf/2018.jsconf.eu/tree/master/contents/copy/sponsors

**Comment by Kriesse** [comment]
We won't have the (2017) logo gallery done by tomorrow, but would be nice to have at least a paragraph that encourages sponsors to reach out to us + our email contact.

**Comment by janl** [comment]
https://github.com/jsconf/2018.jsconf.eu/pull/25
