### ISSUE TITLE
manifest.json is not found

### ISSUE THREAD

**Issue by kotzendekrabbe** [jsconf/2018.jsconf.eu#36]
something with wintersmith and the rout to manifest.json is not working.

**Comment by sfrdmn** [comment]
Ah right, seems Wintersmith is interpreting it as page metadata rather than raw JSON. Will check it out

**Comment by sfrdmn** [comment]
Seems to be an OK solution: https://github.com/jnordberg/wintersmith/issues/281

**Comment by lukaszklis** [comment]
Is this issue still happening? If not, let’s close the ticket. ;)

**Comment by cramforce** [comment]
Fixed in #123
