### ISSUE TITLE
Style Speaker Page

### ISSUE THREAD

**Issue by Kriesse** [jsconf/2018.jsconf.eu#60]
https://files.slack.com/files-tmb/T03KHL2GT-F8DEWUKHU-6a5ad57c3e/speaker-overview-1366_1024.jpg

Responsive Design:
https://drive.google.com/open?id=1AbQJqxvf80H6vsD4Mx0sm-1GLr27Xvyu

**Comment by cramforce** [comment]
#82 has some remaining TODOs
