### ISSUE TITLE
Implement SVG workflow

### ISSUE THREAD

**Issue by Kriesse** [jsconf/2018.jsconf.eu#7]
All icons and svgs are currently used via `<img>`, which has some downsides (svg can't be styled via css, more requests…)

Can we have a workflow like this?
https://www.sitepoint.com/a-working-svg-workflow-for-accessible-icons/

**Comment by sfrdmn** [comment]
I believe there might be one already in place in Martin's skeleton, I just didn't move it over. Will check it out

**Comment by sfrdmn** [comment]
Done but seems that more styling needs to be added to make it look right
